name: Deploy to GitHub Pages with Secrets

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Permisos explícitos para GitHub Actions
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Replace secrets in config.js
      run: |
        echo "🔐 Reemplazando placeholders en config.js..."
        # Reemplazar placeholders con secrets en config.js (compatible con Linux)
        sed -i 's|{{FIREBASE_API_KEY}}|${{ secrets.FIREBASE_API_KEY }}|g' web-html/js/config.js
        sed -i 's|{{FIREBASE_AUTH_DOMAIN}}|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g' web-html/js/config.js
        sed -i 's|{{FIREBASE_PROJECT_ID}}|${{ secrets.FIREBASE_PROJECT_ID }}|g' web-html/js/config.js
        sed -i 's|{{FIREBASE_STORAGE_BUCKET}}|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g' web-html/js/config.js
        sed -i 's|{{FIREBASE_MESSAGING_SENDER_ID}}|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g' web-html/js/config.js
        sed -i 's|{{FIREBASE_APP_ID}}|${{ secrets.FIREBASE_APP_ID }}|g' web-html/js/config.js
        sed -i 's|{{SUPABASE_URL}}|${{ secrets.SUPABASE_URL }}|g' web-html/js/config.js
        sed -i 's|{{SUPABASE_ANON_KEY}}|${{ secrets.SUPABASE_ANON_KEY }}|g' web-html/js/config.js
        echo "✅ Placeholders reemplazados en config.js"
        
    - name: Replace secrets in drivers.js
      run: |
        echo "🔐 Reemplazando placeholders en drivers.js..."
        # Reemplazar placeholders con secrets en drivers.js (compatible con Linux)
        sed -i 's|{{FIREBASE_PROJECT_ID}}|${{ secrets.FIREBASE_PROJECT_ID }}|g' web-html/drivers/drivers.js
        echo "✅ Placeholders reemplazados en drivers.js"

    - name: Replace secrets in home.html
      run: |
        echo "🔐 Reemplazando placeholders en home.html..."
        # Reemplazar placeholders con secrets en home.html (compatible con Linux)
        sed -i 's|{{FIREBASE_API_KEY}}|${{ secrets.FIREBASE_API_KEY }}|g' web-html/home/home.html
        sed -i 's|{{FIREBASE_AUTH_DOMAIN}}|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g' web-html/home/home.html
        sed -i 's|{{FIREBASE_PROJECT_ID}}|${{ secrets.FIREBASE_PROJECT_ID }}|g' web-html/home/home.html
        sed -i 's|{{FIREBASE_STORAGE_BUCKET}}|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g' web-html/home/home.html
        sed -i 's|{{FIREBASE_MESSAGING_SENDER_ID}}|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g' web-html/home/home.html
        sed -i 's|{{FIREBASE_APP_ID}}|${{ secrets.FIREBASE_APP_ID }}|g' web-html/home/home.html
        sed -i 's|{{SUPABASE_URL}}|${{ secrets.SUPABASE_URL }}|g' web-html/home/home.html
        sed -i 's|{{SUPABASE_ANON_KEY}}|${{ secrets.SUPABASE_ANON_KEY }}|g' web-html/home/home.html
        echo "✅ Placeholders reemplazados en home.html"
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: web-html
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
